### ISSUE TITLE
Haven't been able to compile in Android Studio or Eclipse

### ISSUE THREAD

**Issue by bgarr33434** [SamsungDForum/SmartViewSDKPhotoShare#1]
better build instructions?  Thanks

**Comment by bgarr33434** [comment]
Here is my gradle build file
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:5.0'
        compileOnly 'org.projectlombok:lombok:1.14.8'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by bgarr33434** [comment]
Turns out my problem is also that PhotoShareWebApplicationHelper is missing

**Comment by bgarr33434** [comment]
I guess no one monitors their github submissions?

**Comment by ankitsharma246** [comment]
PhotoShareWebApplicationHelper  added

please recheck
